name: Push to Docker Hub

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: docker/quality-control
            name: vulcan-qc
          - dockerfile: docker/taxonomic-analysis
            name: vulcan-ta
          - dockerfile: docker/metagenomics-binning/gtdbtk
            name: vulcan-gtdbtk
          - dockerfile: docker/metagenomics-binning/py27
            name: vulcan-mbpy2
          - dockerfile: docker/metagenomics-binning/py3
            name: vulcan-mbpy3
          - dockerfile: docker/error-correction
            name: vulcan-ec
          - dockerfile: docker/binning
            name: vulcan-binning
          - dockerfile: docker/amos
            name: vulcan-amos

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.name }}:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.name }}:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/${{ matrix.name }}:buildcache,mode=max